### ISSUE TITLE
Unable to export data

### ISSUE THREAD

**Issue by OliverCardoza** [UltimateSoftware/mypay-export#1]
I've followed the README instructions and set up config with my employer's Ultimate domain and auth token but I get the following error:

`Error reading post data: invalid character 'Y' looking for beginning of value ::: You do not have permission to view this directory or page.`

My first thought was that the mobile website was disabled. However, the mobile login page does appear to be enabled here:
$EMPLOYER.ultipro.com/mobile/app/pages/login.aspx?deepLink=Dashboard.aspx

My second thought is that my employer has disabled username + password authentication for employees to prefer the more secure SSO option (uses Google OAuth).

I can't be certain which of the issues is causing the issue. In any case I appreciate the effort here (thanks Joseph!) to try and provide CSV export. Until then I'll go back to `pdfgrep`'ing my PDFs...

**Comment by josephcultimate** [comment]
Hi @OliverCardoza 
Are you able to access the mobile site past the login screen? If you log into UltiPro and you are on the main dashboard after logging in, (https://$EMPLOYER.ultipro.com/default.aspx) replace default.aspx with mobile (https://$EMPLOYER.ultipro.com/mobile) and ensure that you can get to the mobile dashboard. Then make sure you can access the Your Pay section. Doing all this will confirm that you have the correct access rights. Please confirm those steps and we can continue from there

**Comment by OliverCardoza** [comment]
After authenticating on the desktop website via Oauth (https://$EMPLOYER.ultipro.com/default.aspx) and navigating to the mobile website (https://$EMPLOYER.ultipro.com/mobile) I'm kicked out to the mobile log in page (https://google.ultipro.com/mobile/app/pages/login.aspx?deepLink=Dashboard.aspx).

**Comment by OliverCardoza** [comment]
Thanks for checking Joseph. If the above is proof that the mobile site is not enabled then feel free to mark this issue closed, working as intended. I don't think I'll get much traction convincing payroll team to enable the mobile website just so I can use the mobile api to extract data dumps.

**Comment by josephcultimate** [comment]
Ill put a call in to the team over there to see if anyone can reach out and pair up with you. You never know what can happen :)
